name: 'Calculate Version'
description: 'Determines version using GitVersion and writes it to .tags file'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  PROD:
    description: 'Flag indicating whether production is true'
    default: 'false'
outputs:
  VERSION:
    description: 'The version determined by GitVersion'
  GIT_VERSION:
    description: 'The version determined by GitVersion'
  PRODUCTION_BUILD:
    description: 'Bool value if this was a production build'
  BRANCH_NAME:
    description: 'Name of Branch SemVer was calculated for'